
spring.datasource.url=jdbc:postgresql://localhost:5532/cornersdev
#spring.jpa.properties.hibernate.default_schema=corners-dev
spring.datasource.username=dbadmin
spring.datasource.password=coolcorners123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

#keycloak
# === Keycloak JWT issuer ===
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:7070/realms/cool-corners

# (Optional) Logging for debugging
logging.level.org.springframework.security=DEBUG