flyway.user=dbadmin
flyway.password=coolcorners123
flyway.defaultSchema=corners-dev
flyway.url=jdbc:postgresql://cool-corners-db-dev.costvtrb1qnq.eu-central-1.rds.amazonaws.com:5432/cornersdev
flyway.locations=filesystem:db/migration

